version: '3.9'

services:
  db:
    image: mysql:8
    container_name: spring-mq-db
    ports:
      - 3306:3306
    environment:
        TZ: "Asia/Seoul"
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test

  messaging-queue:
    image: rabbitmq:3-management
    container_name: spring-mq-mq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
        TZ: "Asia/Seoul"
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest